CREATE TABLE IF NOT EXISTS `BDLIMABUS`.`manto_vale` (
  `vale_id` INT NOT NULL AUTO_INCREMENT,
  `va_asociado` VARCHAR(50) NULL,
  `va_cierra` VARCHAR(8) NULL,
  `va_cierre_adm` VARCHAR(8) NULL,
  `va_date_cierra` DATETIME NULL,
  `va_date_genera` DATETIME NOT NULL,
  `va_estado` VARCHAR(50) NOT NULL,
  `va_garantia` VARCHAR(45) NULL,
  `va_genera` VARCHAR(8) NOT NULL,
  `va_modif` INT NULL,
  `va_obs_aom` VARCHAR(1000) NULL,
  `va_obs_cgm` VARCHAR(500) NULL,
  `va_recepcion` VARCHAR(10) NULL,
  `va_rep` VARCHAR(10) NULL,
  `va_responsable` VARCHAR(50) NULL,
  `va_tecnico` VARCHAR(8) NULL,
  `va_usurep` VARCHAR(8) NULL,
  `va_tipo` VARCHAR(45) NULL,
  `va_ruc` VARCHAR(11) NULL,
  `va_ot_id` INT NULL,
  `va_almacen_ok` VARCHAR(2) NULL,
  `va_coordinador_ok` VARCHAR(2) NULL,
  PRIMARY KEY (`vale_id`))
ENGINE = InnoDB;