/* Accidentabilidad - Registro de las novedades de accidentes para el calculo de desempeño */
DROP TABLE IF EXISTS `BDLIMABUS`.`accidentabilidad`;
CREATE TABLE `BDLIMABUS`.`accidentabilidad` (
  `Accidentabilidad_id` int NOT NULL AUTO_INCREMENT,
  `Acci_CodApl` int DEFAULT NULL,
  `Acci_FechaAccidente` date DEFAULT NULL,
  `Acci_HoraDeAccidente` time DEFAULT NULL,
  `Acci_NombreDeCgo` varchar(45) DEFAULT NULL,
  `Acci_DniPiloto` varchar(8) DEFAULT NULL,
  `Acci_CodigoPiloto` varchar(6) DEFAULT NULL,
  `Acci_NombreDePiloto` varchar(60) DEFAULT NULL,
  `Acci_FechaDeIngreso` date DEFAULT NULL,
  `Acci_AntiguedadDePiloto` varchar(100) DEFAULT NULL,
  `Acci_Tabla` varchar(45) DEFAULT NULL,
  `Acci_NumBus` varchar(45) DEFAULT NULL,
  `Acci_Servicio` varchar(45) DEFAULT NULL,
  `Acci_DireccionAccidente` varchar(80) DEFAULT NULL,
  `Acci_SentidoAccidente` varchar(45) DEFAULT NULL,
  `Acci_ClaseDeAccidente` varchar(45) DEFAULT NULL,
  `Acci_Evento` varchar(70) DEFAULT NULL,
  `Acci_OcurrenciaAccidente` varchar(2450) DEFAULT NULL,
  `Acci_PilotoReconoceResponsabilidad` varchar(20) DEFAULT NULL,
  `Acci_DañosVehiculoLbi` varchar(800) DEFAULT NULL,
  `Acci_Conciliado` varchar(20) DEFAULT NULL,
  `Acci_Moneda` varchar(45) DEFAULT NULL,
  `Acci_Monto` decimal(6,2) DEFAULT NULL,
  `Acci_TramitePolicial` varchar(45) DEFAULT NULL,
  `Acci_AsistioAccidente` varchar(45) DEFAULT NULL,
  `Acci_FaltaCometidaPorElPiloto` varchar(80) DEFAULT NULL,
  `Acci_FaltaCometida2` varchar(80) DEFAULT NULL,
  `Acci_ResponsabilidadDeFalta2` varchar(20) DEFAULT NULL,
  `Acci_GravedadDeEvento` varchar(45) DEFAULT NULL,
  `Acci_CostoTotalDeAccidente` decimal(9,2) DEFAULT NULL,
  `Acci_Responsabilidad` varchar(45) DEFAULT NULL,
  `Acci_FechaCarga` datetime DEFAULT NULL,
  PRIMARY KEY (`Accidentabilidad_id`)
) ENGINE=InnoDB AUTO_INCREMENT=5422 DEFAULT CHARSET=utf8mb3