CREATE TABLE `BDLIMABUS`.`OPE_Novedad` (
  `OPE_NovedadId` int(11) NOT NULL,
  `Novedad_Id` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_ProgramacionId` int(11) NOT NULL,
  `Nove_Novedad` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_TipoNovedad` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_DetalleNovedad` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_Descripcion` varchar(1500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_Operacion` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_FechaOperacion` date NOT NULL,
  `Nove_Dni` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_CodigoColaborador` CHARACTER SET utf8 COLLATE utf8_general_ci varchar(4) NOT NULL,
  `Nove_NombreColaborador` CHARACTER SET utf8 COLLATE utf8_general_ci varchar(60) NOT NULL,
  `Nove_Tabla` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_HoraOrigen` time NOT NULL,
  `Nove_HoraDestino` time NOT NULL,
  `Nove_Servicio` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_Bus` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_LugarOrigen` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_LugarDestino` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_LugarExacto` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Nove_HoraInicio` time DEFAULT NULL,
  `Nove_HoraFin` time DEFAULT NULL,
  `Nove_Estado` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_UsuarioId` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_ProcesoOrigen` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `Nove_Fecha` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Nove_CFaRgId` int(11) NOT NULL,
  `Nove_UsuarioId_Edicion` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Nove_FechaEdicion` timestamp NULL DEFAULT NULL,
  `Nove_UsuarioId_Eliminar` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Nove_FechaEliminar` timestamp NULL DEFAULT NULL,
  `Nove_UsuarioId_Cerrar` varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `Nove_FechaCerrar` timestamp NULL DEFAULT NULL,
  `Nove_Version` int(11) NOT NULL
  `Nove_TipoOrigen` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
