CREATE TABLE `BDLIMABUS`.`ope_comportamiento` ( 
`ope_comportamientoid`  INT(11) NOT NULL AUTO_INCREMENT ,
`comportamiento_id` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_programacionid` INT(11) NOT NULL , 
`comp_controlfacilitadorid` INT(11) NOT NULL , 
`comp_openovedadid` INT(11) NOT NULL , 
`comp_novedadid` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_novedad` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_tiponovedad` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_tipoorigen` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_detallenovedad` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_descripcion` VARCHAR(1500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_operacion` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_fechaoperacion` DATE NOT NULL , 
`comp_estadocomportamiento` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_dni` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_codigocolaborador` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_nombrecolaborador` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_codigocgo` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_nombrecgo` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`comp_tabla` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_servicio` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_bus` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_lugarexacto` varchar(250) NOT NULL,
`comp_horainicio` time NOT NULL,
`comp_horafin` time NOT NULL,
`comp_linkvideo` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_grado_falta` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_codigofalta` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_faltacometida` VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_monto` FLOAT NULL ,
`comp_reconoceresponsabilidad` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`comp_reportegdh` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_fechareportegdh` DATE NULL DEFAULT NULL ,
`comp_premio` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`comp_cfargid` INT(11) NOT NULL , 
`comp_telemetriacargaid` INT(11) NOT NULL , 
`comp_usuarioid_generar` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_fechagenerar` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`comp_usuarioid_edicion` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`comp_fechaedicion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`comp_usuarioid_cerrar` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_fechacerrar`  TIMESTAMP NULL DEFAULT NULL,
`comp_log` VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_cargo_colaborador` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_lugar_origen` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_lugar_destino` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_turno` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`comp_total_horas` time NOT NULL,
PRIMARY KEY (`ope_comportamientoid`)) ENGINE = InnoDB;


INSERT INTO `BDLIMABUS`.`ope_comportamiento`
(`comportamiento_id`,
`comp_programacionid`,
`comp_controlfacilitadorid`,
`comp_openovedadid`,
`comp_novedadid`,
`comp_novedad`,
`comp_tiponovedad`,
`comp_tipoorigen`,
`comp_detallenovedad`,
`comp_descripcion`,
`comp_operacion`,
`comp_fechaoperacion`,
`comp_estadocomportamiento`,
`comp_dni`,
`comp_codigocolaborador`,
`comp_nombrecolaborador`,
`comp_codigocgo`,
`comp_nombrecgo`,
`comp_tabla`,
`comp_servicio`,
`comp_bus`,
`comp_lugarexacto`,
`comp_horainicio`,
`comp_horafin`,
`comp_linkvideo`,
`comp_codigofalta`,
`comp_faltacometida`,
`comp_monto`,
`comp_reconoceresponsabilidad`,
`comp_reportegdh`,
`comp_fechareportegdh`,
`comp_premio`,
`comp_cfargid`,
`comp_telemetriacargaid`,
`comp_usuarioid_generar`,
`comp_fechagenerar`,
`comp_usuarioid_edicion`,
`comp_fechaedicion`,
`comp_usuarioid_cerrar`,
`comp_fechacerrar`,
`comp_log`,
`comp_cargo_colaborador`,
`comp_lugar_origen`,
`comp_lugar_destino`,
`comp_turno`,
`comp_total_horas`)
SELECT 
	`comportamiento`.`Comp_ID`,
    '0',
    '0',
    '0',
    `comportamiento`.`Comp_ID`,
    'NOVEDAD_PILOTO',
    `comportamiento`.`Comp_DetalleNovedad`,
    'CGO',
    'SIN_PERDIDA_KM',
    `comportamiento`.`Comp_DescripNovedad`,
    IF(`comportamiento`.`Comp_TipoPiloto`='ARTICULADO','TRONCAL',`comportamiento`.`Comp_TipoPiloto`),
    `comportamiento`.`Comp_FechaEvento`,
    IF(`comportamiento`.`Comp_AfectaPremio`='SI','CIERRE OPERACIONAL','ANULADO OPERACIONAL'),
    `comportamiento`.`Comp_Dni`,
    `comportamiento`.`Comp_CodPiloto`,
    `comportamiento`.`Comp_NombrePiloto`,
	'0',
    `comportamiento`.`Comp_Nombre CGO`,
    `comportamiento`.`Comp_Tabla`,
    `comportamiento`.`Comp_Servicio`,    
    `comportamiento`.`Comp_Bus`,
    '-',
    '00:00:00',
    '00:00:00',
    '-',
    `comportamiento`.`Comp_CodigoDeFalta`,
    `comportamiento`.`Comp_AccionDisciplinaria`,
    `comportamiento`.`Comp_Monto`,
    IF(`comportamiento`.`Comp_ReconoceResp`='SI','SI','NO'),
    `comportamiento`.`Comp_AfectaPremio`,
    `comportamiento`.`Comp_FechaCarga`,
	IF(`comportamiento`.`Comp_AfectaPremio`='SI','NO','SI'),
    '0',
    '0',
    '41782444',
    '2023-05-29 08:28:20',
    '41782444',
    '2023-05-29 08:28:20',
    '41782444',
    '2023-05-29 08:28:20',
    CONCAT(IF(`comportamiento`.`Comp_AfectaPremio`='SI','CIERRE OPERACIONAL','ANULADO OPERACIONAL'),' 2023-05-09 JOEL VALENCIA CREAR: POR SISTEMA'),
    `comportamiento`.`Comp_TipoPiloto`,
    '',
    '',
    '',
    '00:00:00'
FROM `BDLIMABUS`.`comportamiento`;