CREATE TABLE `BDLIMABUS`.`OPE_AccidentesInformePreliminar` ( 
`OPE_AcciInformePreliminarId`  INT(11) NOT NULL AUTO_INCREMENT ,
`Accidentes_Id` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_Operacion` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_TipoAccidente` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_ClaseAccidente` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_DanosMateriales` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Lesiones` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Fatalidad` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Otro` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_OtroDescripcion` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_TipoEvento` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Fecha` DATE NOT NULL , 
`Acci_Hora` TIME NOT NULL ,
`Acci_Dni` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_CodigoColaborador` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_NombreColaborador` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_Tabla` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_Servicio` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_Bus` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_Lugar` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Sentido` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_CodigoCGO` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_NombreCGO`  VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_CodigoPersonalApoyo` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,  
`Acci_NombrePersonalApoyo` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_km_perdidos` FLOAT NULL ,
`Acci_Conciliacion`  VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_MontoConciliado` FLOAT NULL , 
`Acci_Hospital` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_ReconoceResponsabilidad` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Comisaria` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocReporte` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocConciliacion` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocPartePolicial` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocOficioPeritaje` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocReporteAtencion` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocDenunciaPolicial` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocCitacionManifestacion` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocOtro` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DocOtroDescripcion` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_HoraFinAtencion` TIME NOT NULL ,
`Acci_HorasTrabajadas` TIME NULL ,
`Acci_Descripcion` VARCHAR(1500) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_CodigoSuscribeInformacion` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_NombreSuscribeInformacion` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_FechaElaboracionInforme` TIMESTAMP NULL DEFAULT NULL ,
`Acci_Objeto` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_HoraLlegadaProcurador` TIME NULL ,
`Acci_CodigoCGM` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_NombreCGM`  VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_CodigoPersonalApoyoManto` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,  
`Acci_NombrePersonalApoyoManto` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_NumeroOT` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_EstadoInformePreliminar` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_UsuarioId_Generar` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_FechaGenerar` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`Acci_UsuarioId_Edicion` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_FechaEdicion`  TIMESTAMP NULL DEFAULT NULL,
`Acci_UsuarioId_Cerrar` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_FechaCerrar`  TIMESTAMP NULL DEFAULT NULL,
`acci_log_ip` VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`acci_lugar_referencia` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
PRIMARY KEY (`OPE_AcciInformePreliminarId`)) ENGINE = InnoDB;