CREATE TABLE `BDLIMABUS`.`OPE_AccidentesInvestigacion` ( 
`OPE_AcciInvestigacionId`  INT(11) NOT NULL AUTO_INCREMENT ,
`Accidentes_Id` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_DatosRegistro` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Trafico` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_LugarReferencia` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_FactorDeterminante` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_ResponsabilidadDeterminante` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_FactorContributivo` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_ResponsabilidadContributivo` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_TipoExpediente` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_EventoReportado` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_Frecuencia` INT(2) NULL , 
`Acci_Probabilidad` INT(2) NULL , 
`Acci_Severidad` INT(2) NULL , 
`Acci_GravedadEvento` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_ResponsabilidadAccidente` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_GradoFalta` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_Reincidencia` INT(2) NULL , 
`Acci_CodigoRIT` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_DescripcionRIT` VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_AccionDisciplinaria` VARCHAR(250) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_ReporteGDH` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_FechaReporteGDH` DATE NULL DEFAULT NULL ,
`Acci_Premio` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_FechaCierreAccidente` DATE NULL DEFAULT NULL ,
`Acci_TiempoInvestigacion` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_CumplimientoMeta` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_DelayRegistro` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_CumplimientoRegistro` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_FechaRegistro` DATE NULL DEFAULT NULL ,
`Acci_EstadoInvestigacion` VARCHAR(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
`Acci_FechaCierreReporte` DATE NULL DEFAULT NULL ,
`Acci_LogInvestigacion` VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL , 
`Acci_UsuarioId_Cierre` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
`Acci_Fecha_Cierre` TIMESTAMP NULL ,
`acci_nro_siniestro` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL ,
PRIMARY KEY (`OPE_AcciInvestigacionId`)) ENGINE = InnoDB;