CREATE TABLE `BDLIMABUS`.`ControlFacilitador` ( 
     `ControlFacilitador_Id` INT(11) NOT NULL AUTO_INCREMENT ,
     `Programacion_Id` INT(11) NOT NULL ,
     `Prog_Codigo` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
     `Prog_Operacion` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_Fecha` DATE NOT NULL , 
     `Prog_Dni` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_CodigoColaborador` VARCHAR(4) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_NombreColaborador` VARCHAR(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_Tabla` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_HoraOrigen` TIME NOT NULL , 
     `Prog_HoraDestino` TIME NOT NULL , 
     `Prog_Servicio` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_ServBus` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_Bus` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_LugarOrigen` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_LugarDestino` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_TipoEvento` VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_Observaciones` VARCHAR(120) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_KmXPuntos` FLOAT NOT NULL , 
     `Prog_TipoTabla` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_NPlaca` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_NVid` VARCHAR(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_IdManto` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_Sentido` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_BusManto` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `Prog_Viajes` VARCHAR(45) CHARACTER SET utf8 NOT NULL ,
     `CFaRg_Id` INT(11) NOT NULL ,
     `CFaci_Estado` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `CFaci_UsuarioId` VARCHAR(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
     `CFaci_Novedad` VARCHAR(2) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL ,
     `CFaci_ProcesoOrigen` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , 
     `CFaci_Version` int(11) NOT NULL ,
     `CFaci_Campo1` VARCHAR(45) CHARACTER SET utf8 NOT NULL ,
     `CFaci_Campo2` VARCHAR(45) CHARACTER SET utf8 NOT NULL ,
     `CFaci_Campo3` VARCHAR(45) CHARACTER SET utf8 NOT NULL ,
PRIMARY KEY (`ControlFacilitador_Id`)) ENGINE = InnoDB;
