CREATE TABLE `BDLIMABUS`.`ope_despachoflota` (
  `despachoflota_id` int(11) NOT NULL AUTO_INCREMENT,
  `dflo_dfrgid` int(11) NOT NULL,
  `ControlFacilitador_Id` int(11) NOT NULL,
  `Programacion_Id` int(11) NOT NULL,
  `Prog_Codigo` varchar(45) NOT NULL,
  `Prog_Operacion` varchar(45) NOT NULL,
  `Prog_Fecha` date NOT NULL,
  `Prog_Dni` varchar(8) NOT NULL,
  `Prog_CodigoColaborador` varchar(4) NOT NULL,
  `Prog_NombreColaborador` varchar(60) NOT NULL,
  `Prog_Tabla` varchar(45) NOT NULL,
  `Prog_HoraOrigen` time NOT NULL,
  `Prog_HoraDestino` time NOT NULL,
  `Prog_Servicio` varchar(45) NOT NULL,
  `Prog_ServBus` varchar(45) NOT NULL,
  `Prog_Bus` varchar(45) NOT NULL,
  `Prog_LugarOrigen` varchar(50) NOT NULL,
  `Prog_LugarDestino` varchar(50) NOT NULL,
  `Prog_TipoEvento` varchar(50) NOT NULL,
  `Prog_Observaciones` varchar(120) NOT NULL,
  `Prog_KmXPuntos` float NOT NULL,
  `Prog_TipoTabla` varchar(45) NOT NULL,
  `Prog_NPlaca` varchar(45) NOT NULL,
  `Prog_NVid` varchar(45) NOT NULL,
  `Prog_IdManto` varchar(45) NOT NULL,
  `Prog_Sentido` varchar(45) NOT NULL,
  `Prog_BusManto` varchar(45) NOT NULL,
  `CFaRg_Id` int(11) NOT NULL,
  `CFaci_Estado` varchar(15) NOT NULL,
  `CFaci_UsuarioId` varchar(8) NOT NULL,
  `CFaci_Novedad` varchar(2) DEFAULT NULL,
  `CFaci_ProcesoOrigen` varchar(15) NOT NULL,
  `CFaci_Version` int(11) NOT NULL,
  `dflo_nrodespacho` int(11) NULL,
  `dflo_tablacorta` varchar(45) NULL,
  `dflo_horainiciotabla` time NULL,
  `dflo_horaterminotabla` time NULL,
  `dflo_kmtotal` float NULL,
  `dflo_turno` varchar(45) NULL,
  `dflo_obsmanto` varchar(120) NULL,
  `dflo_horaentregamanto` time NULL,
  `dflo_horaentregamantoreal`  time NULL,
  `dflo_cambiobusentregamanto` varchar(45) NULL,
  `dflo_ontimeentregamanto` time NULL,
  `dflo_estatusentregamanto` varchar(45) NULL,
  `dflo_motivoretrasoentregamanto` varchar(120) NULL,
  `dflo_horasalidareal` time NULL,
  `dflo_cambiobussalida` varchar(45) NULL,
  `dflo_ontimesalida` time NULL,
  `dflo_estatussalida` varchar(45) NULL,
  `dflo_motivoretrasosalida` varchar(120) NULL,
PRIMARY KEY (`despachoflota_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;