/* ELIMINA LAS BASE DE DATOS DEL SERVIDOR Y LAS VUELVE A CREAR EN BLANCO PARA CARGARLAS CON LA DATA EXTRAIDA*/

DROP DATABASE IF EXISTS `BDLIMABUS`;
DROP DATABASE IF EXISTS `BDLIMABUS2`;
DROP DATABASE IF EXISTS `csitecco_lbi1`;
DROP DATABASE IF EXISTS `bdlimabus_hist`;
DROP DATABASE IF EXISTS `bdlimabus_imag`;
CREATE DATABASE `BDLIMABUS` CHARACTER SET utf8;
CREATE DATABASE `BDLIMABUS2` CHARACTER SET utf8;
CREATE DATABASE `csitecco_lbi1` CHARACTER SET utf8;
CREATE DATABASE `bdlimabus_hist` CHARACTER SET utf8;
CREATE DATABASE `bdlimabus_imag` CHARACTER SET utf8;